// <auto-generated />
using System;
using ChatWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatWebsite.Migrations
{
    [DbContext(typeof(WebApp1Context))]
    partial class WebApp1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApplication1.Models.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

<<<<<<< Updated upstream:WebApplication1/Migrations/WebApp1/WebApp1ContextModelSnapshot.cs
                    b.HasKey("ID", "UserId");

                    b.HasIndex("UserId");
=======
                    b.HasKey("Id", "UserId");
>>>>>>> Stashed changes:WebApplication1/Migrations/WebApp1ContextModelSnapshot.cs

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("WebApplication1.Models.Rating", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DateTime")
                        .HasColumnType("longtext");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Score")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("WebApplication1.Models.TextMessage", b =>
                {
<<<<<<< Updated upstream:WebApplication1/Migrations/WebApp1/WebApp1ContextModelSnapshot.cs
                    b.Property<int>("ID")
=======
                    b.Property<int>("Id")
>>>>>>> Stashed changes:WebApplication1/Migrations/WebApp1ContextModelSnapshot.cs
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactId")
<<<<<<< Updated upstream:WebApplication1/Migrations/WebApp1/WebApp1ContextModelSnapshot.cs
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactID")
=======
>>>>>>> Stashed changes:WebApplication1/Migrations/WebApp1ContextModelSnapshot.cs
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("UserSent")
                        .HasColumnType("tinyint(1)");

<<<<<<< Updated upstream:WebApplication1/Migrations/WebApp1/WebApp1ContextModelSnapshot.cs
                    b.HasKey("ID", "UserId", "ContactId");

                    b.HasIndex("ContactID", "ContactUserId");
=======
                    b.HasKey("Id", "UserId", "ContactId");
>>>>>>> Stashed changes:WebApplication1/Migrations/WebApp1ContextModelSnapshot.cs

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
<<<<<<< Updated upstream:WebApplication1/Migrations/WebApp1/WebApp1ContextModelSnapshot.cs

            modelBuilder.Entity("WebApplication1.Models.Contact", b =>
                {
                    b.HasOne("WebApplication1.Models.User", null)
                        .WithMany("Contacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.TextMessage", b =>
                {
                    b.HasOne("WebApplication1.Models.Contact", null)
                        .WithMany("Messages")
                        .HasForeignKey("ContactId");
                });

            modelBuilder.Entity("WebApplication1.Models.Contact", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Navigation("Contacts");
                });
=======
>>>>>>> Stashed changes:WebApplication1/Migrations/WebApp1ContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
